/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** First-run owner creation. 409 `already_setup` once any user exists. */
        post: operations["authSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email and password. 401 `invalid_credentials` on failure. */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session. Idempotent. */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user. 401 `unauthenticated` or `session_expired` otherwise. */
        get: operations["authMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mint a one-time invite link (owner only). The raw token appears here once. */
        post: operations["createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{token}/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join via an invite link. 404 `invite_invalid` for an unknown or used token, 410 `invite_expired` past expiry, 409 `email_taken`. */
        post: operations["redeemInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Registered modules and their post-boot state. */
        get: operations["systemModules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query the audit log (owner only). Keyset-paginated. */
        get: operations["auditList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The SSE stream (contracts §5.1). One connection per tab; `?topics=project:PAY,run:01H…,inbox` selects topics. Frames carry `id:` (ULID), `event:` (StreamEventType) and `data:` (StreamFrame). `Last-Event-ID` on reconnect replays missed frames. Not consumable through fetch — the SPA uses EventSource. */
        get: operations["stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 problem details. `type` is a slug, not a URL. Slugs in use today: setup_required, already_setup, invalid_credentials, session_expired, unauthenticated, forbidden, invite_invalid, invite_expired, email_taken, not_found, invalid_request, validation_failed, internal. */
        Problem: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        FieldError: {
            field: string;
            message: string;
        };
        User: {
            id: string;
            email: string;
            display_name: string;
            /** @enum {string} */
            role: "owner" | "member";
            avatar_color: string;
            /** Format: date-time */
            created_at: string;
        };
        SetupRequest: {
            email: string;
            display_name: string;
            password: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        RedeemRequest: {
            email: string;
            display_name: string;
            password: string;
        };
        Invite: {
            /** @description The one-time path (`/invite/<token>`) the owner copies into a message. */
            path: string;
            /** Format: date-time */
            expires_at: string;
        };
        ModulesResponse: {
            modules: components["schemas"]["ModuleStatus"][];
        };
        ModuleStatus: {
            name: string;
            /** @enum {string} */
            state: "ready" | "degraded";
            reason?: string;
        };
        AuditListResponse: {
            entries: components["schemas"]["AuditEntry"][];
            /** @description Present exactly when the page was full; pass back as ?cursor=. */
            next_cursor?: string;
        };
        AuditEntry: {
            id: string;
            project_id: string | null;
            actor_kind: string;
            actor_id: string | null;
            action: string;
            target_kind: string;
            target_id: string;
            before: unknown;
            after: unknown;
            note?: string;
            /** Format: date-time */
            created_at: string;
        };
        /**
         * @description The SSE `event:` names (contracts §5.1).
         * @enum {string}
         */
        StreamEventType: "run.state" | "run.activity" | "run.step" | "run.usage" | "run.elicitation" | "ticket.updated" | "board.updated" | "triage.created" | "trigger.fired" | "notification.updated" | "wiki.proposed" | "provision.step" | "module.degraded";
        /** @description The `data:` payload of every SSE frame. */
        StreamFrame: {
            topic: string;
            payload: unknown;
        };
    };
    responses: {
        /** @description application/problem+json with a stable `type` slug. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Owner created and signed in (session cookie set). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in (session cookie set). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked and cookie cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The copyable invite path and its expiry. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invite"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    redeemInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeemRequest"];
            };
        };
        responses: {
            /** @description Member created and signed in (session cookie set). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            410: components["responses"]["Problem"];
        };
    };
    systemModules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The module list. Empty list, never null. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModulesResponse"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    auditList: {
        parameters: {
            query?: {
                /** @description Project key or id. */
                project?: string;
                /** @description `human` or `human:<id>` (later: agent, trigger, system). */
                actor?: string;
                action?: string;
                /** @description Target kind. */
                target?: string;
                since?: string;
                until?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of audit entries, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditListResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    stream: {
        parameters: {
            query?: {
                /** @description Comma-separated topic list. */
                topics?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An event stream; stays open until the client goes away. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Problem"];
        };
    };
}
