/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** First-run owner creation. 409 `already_setup` once any user exists. */
        post: operations["authSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email and password. 401 `invalid_credentials` on failure. */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session. Idempotent. */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user. 401 `unauthenticated` or `session_expired` otherwise. */
        get: operations["authMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mint a one-time invite link (owner only). The raw token appears here once. */
        post: operations["createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{token}/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join via an invite link. 404 `invite_invalid` for an unknown or used token, 410 `invite_expired` past expiry, 409 `email_taken`. */
        post: operations["redeemInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Registered modules and their post-boot state. */
        get: operations["systemModules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projects with Home-table stats (UI spec §5.1), oldest first. Archived projects are excluded unless ?archived=1. */
        get: operations["listProjects"];
        put?: never;
        /** Create a project; the caller becomes owner and first member. A duplicate or malformed key is a 400 `validation_failed` problem naming the `key` field. Settings columns start null (inherit from workspace); board columns arrive with S09. */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One project, with its settings resolved against the workspace defaults. */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch a project. Absent fields are unchanged. The inheritable settings (daily_budget_cents, context_threshold_tokens, verification_days) are tri-state: a number overrides the workspace default, an explicit null reverts to inherit. `archived` true/false archives and unarchives. */
        patch: operations["updateProject"];
        trace?: never;
    };
    "/projects/{key}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The Overview About card (UI spec §5.2) — the fields that exist through S08. `repo` is null until a repository is connected (S14); recent runs, pinned pages and the activity feed arrive with their stories. */
        get: operations["projectOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{key}/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A project's board columns in board order, with ticket counts. Names are display strings; automation keys off `category` (plan rule 3), never the name. */
        get: operations["listColumns"];
        put?: never;
        /** Add a column at the end of the board. Category is chosen at creation (and editable later) — it is what automation reads. */
        post: operations["createColumn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/columns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a column. If it holds tickets, `destination_column_id` names the column that receives them (same board, not the column itself) and the move happens in the delete's transaction; omitting it is a 400 `validation_failed` naming the field. Deleting the project's last backlog/running/done column is a 409 `last_category_column` problem naming the category. */
        delete: operations["deleteColumn"];
        options?: never;
        head?: never;
        /** Patch a column: rename, category, WIP limit (null clears), auto_start_delegate, reorder via `after_id` (null = move to the front, a column id = place after it). Changing the category of the project's last backlog/running/done column is a 409 `last_category_column` problem naming the category. */
        patch: operations["updateColumn"];
        trace?: never;
    };
    "/workspace/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The single workspace_settings row (owner only). */
        get: operations["getWorkspaceSettings"];
        /** Update the workspace settings (owner only). Absent fields are unchanged, so the settings screen can autosave one control at a time. Projects whose settings columns are null follow the new values immediately. */
        put: operations["updateWorkspaceSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query the audit log (owner only). Keyset-paginated. */
        get: operations["auditList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The SSE stream (contracts §5.1). One connection per tab; `?topics=project:PAY,run:01H…,inbox` selects topics. Frames carry `id:` (ULID), `event:` (StreamEventType) and `data:` (StreamFrame). `Last-Event-ID` on reconnect replays missed frames. Not consumable through fetch — the SPA uses EventSource. */
        get: operations["stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 problem details. `type` is a slug, not a URL. Slugs in use today: setup_required, already_setup, invalid_credentials, session_expired, unauthenticated, forbidden, invite_invalid, invite_expired, email_taken, not_found, invalid_request, validation_failed, last_category_column, internal. */
        Problem: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        FieldError: {
            field: string;
            message: string;
        };
        User: {
            id: string;
            email: string;
            display_name: string;
            /** @enum {string} */
            role: "owner" | "member";
            avatar_color: string;
            /** Format: date-time */
            created_at: string;
        };
        SetupRequest: {
            email: string;
            display_name: string;
            password: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        RedeemRequest: {
            email: string;
            display_name: string;
            password: string;
        };
        Invite: {
            /** @description The one-time path (`/invite/<token>`) the owner copies into a message. */
            path: string;
            /** Format: date-time */
            expires_at: string;
        };
        ModulesResponse: {
            modules: components["schemas"]["ModuleStatus"][];
        };
        ModuleStatus: {
            name: string;
            /** @enum {string} */
            state: "ready" | "degraded";
            reason?: string;
        };
        AuditListResponse: {
            entries: components["schemas"]["AuditEntry"][];
            /** @description Present exactly when the page was full; pass back as ?cursor=. */
            next_cursor?: string;
        };
        AuditEntry: {
            id: string;
            project_id: string | null;
            actor_kind: string;
            actor_id: string | null;
            action: string;
            target_kind: string;
            target_id: string;
            before: unknown;
            after: unknown;
            note?: string;
            /** Format: date-time */
            created_at: string;
        };
        /** @description One inheritable project setting resolved against the workspace default (data model §1): `value` is the effective value, `inherited` is whether the project column is null, and `workspace_value` is the live workspace default — everything the InheritedField control needs without recomputing. */
        InheritedInt: {
            value: number;
            inherited: boolean;
            workspace_value: number;
        };
        ProjectSettings: {
            daily_budget_cents: components["schemas"]["InheritedInt"];
            context_threshold_tokens: components["schemas"]["InheritedInt"];
            verification_days: components["schemas"]["InheritedInt"];
        };
        Project: {
            id: string;
            /** @description Uppercase, 2–10 chars: [A-Z][A-Z0-9]{1,9}. */
            key: string;
            name: string;
            description: string;
            color: string;
            owner_id: string;
            agent_guidance: string;
            /** Format: date-time */
            archived_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            settings: components["schemas"]["ProjectSettings"];
        };
        /** @description The Home-table counters (UI spec §5.1). */
        ProjectStats: {
            open_tickets: number;
            running_agents: number;
            needs_you: number;
            spend_today_cents: number;
            /** Format: date-time */
            last_activity: string;
        };
        ProjectListItem: components["schemas"]["Project"] & {
            stats: components["schemas"]["ProjectStats"];
        };
        ProjectListResponse: {
            projects: components["schemas"]["ProjectListItem"][];
        };
        CreateProjectRequest: {
            key: string;
            name: string;
            description?: string;
            /** @description #rrggbb; defaults from a palette when omitted. */
            color?: string;
        };
        /** @description Every field optional; absent = unchanged. The three inheritable settings accept an explicit null to revert to inheriting the workspace default. */
        UpdateProjectRequest: {
            name?: string;
            description?: string;
            color?: string;
            owner_id?: string;
            agent_guidance?: string;
            archived?: boolean;
            daily_budget_cents?: number | null;
            context_threshold_tokens?: number | null;
            verification_days?: number | null;
        };
        ProjectOverview: {
            project: components["schemas"]["Project"];
            owner: components["schemas"]["ProjectOwner"];
            /** @description Null until a repository is connected (S14). */
            repo: Record<string, never> | null;
            agent_count: number;
            open_tickets: number;
            runs_today: number;
            spend_today_cents: number;
        };
        ProjectOwner: {
            id: string;
            display_name: string;
            avatar_color: string;
        };
        /**
         * @description The stable key automation reads (brief D2 / plan rule 3). Code branches on this, never on a column's user-facing name.
         * @enum {string}
         */
        ColumnCategory: "backlog" | "ready" | "running" | "review" | "done" | "canceled";
        Column: {
            id: string;
            project_id: string;
            /** @description A display string; renaming changes nothing functional. */
            name: string;
            category: components["schemas"]["ColumnCategory"];
            /** @description Gap-spaced board ordering; treat as opaque and sort by it. */
            position: number;
            /** @description Null means no limit. */
            wip_limit: number | null;
            /** @description Tickets moved into this column automatically start their delegate agent — agent runs cost money, so the UI requires an explicit confirm to enable it. */
            auto_start_delegate: boolean;
            ticket_count: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ColumnListResponse: {
            columns: components["schemas"]["Column"][];
        };
        CreateColumnRequest: {
            name: string;
            category: components["schemas"]["ColumnCategory"];
        };
        /** @description Every field optional; absent = unchanged. `wip_limit` accepts an explicit null to clear the limit. `after_id` reorders: null moves the column to the front, a column id places it immediately after that column. */
        UpdateColumnRequest: {
            name?: string;
            category?: components["schemas"]["ColumnCategory"];
            wip_limit?: number | null;
            auto_start_delegate?: boolean;
            after_id?: string | null;
        };
        WorkspaceSettings: {
            default_branch: string;
            default_branch_template: string;
            /** @enum {string} */
            default_network_policy: "none" | "allowlist" | "open";
            default_daily_budget_cents: number;
            default_context_threshold_tokens: number;
            default_verification_days: number;
            max_concurrent_containers: number;
            poll_interval_seconds: number;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Every field optional; absent = unchanged. */
        UpdateWorkspaceSettingsRequest: {
            default_branch?: string;
            default_branch_template?: string;
            /** @enum {string} */
            default_network_policy?: "none" | "allowlist" | "open";
            default_daily_budget_cents?: number;
            default_context_threshold_tokens?: number;
            default_verification_days?: number;
            max_concurrent_containers?: number;
            poll_interval_seconds?: number;
        };
        /**
         * @description The SSE `event:` names (contracts §5.1).
         * @enum {string}
         */
        StreamEventType: "run.state" | "run.activity" | "run.step" | "run.usage" | "run.elicitation" | "ticket.updated" | "board.updated" | "triage.created" | "trigger.fired" | "notification.updated" | "wiki.proposed" | "provision.step" | "module.degraded";
        /** @description The `data:` payload of every SSE frame. */
        StreamFrame: {
            topic: string;
            payload: unknown;
        };
    };
    responses: {
        /** @description application/problem+json with a stable `type` slug. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Owner created and signed in (session cookie set). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in (session cookie set). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked and cookie cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The copyable invite path and its expiry. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invite"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    redeemInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeemRequest"];
            };
        };
        responses: {
            /** @description Member created and signed in (session cookie set). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            410: components["responses"]["Problem"];
        };
    };
    systemModules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The module list. Empty list, never null. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModulesResponse"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                /** @description Include archived projects. */
                archived?: "1" | "true";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The project list. Empty list, never null. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description The created project. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The project. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description The updated project. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    projectOverview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The About card data. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOverview"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    listColumns: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The column list. Every project has at least backlog, running and done. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnListResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    createColumn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateColumnRequest"];
            };
        };
        responses: {
            /** @description The created column. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Column"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    deleteColumn: {
        parameters: {
            query?: {
                /** @description Where the column's tickets go. Required when the column holds tickets. */
                destination_column_id?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted (and tickets moved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    updateColumn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateColumnRequest"];
            };
        };
        responses: {
            /** @description The updated column. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Column"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    getWorkspaceSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workspace settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceSettings"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    updateWorkspaceSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkspaceSettingsRequest"];
            };
        };
        responses: {
            /** @description The updated workspace settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceSettings"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    auditList: {
        parameters: {
            query?: {
                /** @description Project key or id. */
                project?: string;
                /** @description `human` or `human:<id>` (later: agent, trigger, system). */
                actor?: string;
                action?: string;
                /** @description Target kind. */
                target?: string;
                since?: string;
                until?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of audit entries, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditListResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    stream: {
        parameters: {
            query?: {
                /** @description Comma-separated topic list. */
                topics?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An event stream; stays open until the client goes away. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Problem"];
        };
    };
}
